name: Main workflow
on: [push]

jobs:
  complile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: prepare
        run: |
          bundle install
          npm install
          bridgetown deploy
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWSACCESS }}
          aws-secret-access-key: ${{ secrets.AWSSECRET }}
          aws-region: us-east-1
      - name: deploy
        run: aws s3 sync output/ s3://devel.link --delete
