name: Main workflow
on: [push]

jobs:
  complile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
      - name: prepare
        run: |
          bundle install
          npm install
          bridgetown deploy
